# Required fields are `version` and `updates`
version: 2
updates:
  # Required fields are `package-ecosystem`, `directory`, and `schedule.interval`

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "-Dependencies"
      - "G-DevOps-QA"
    reviewers:
      - "NUbots/Active/Devops"
    schedule:
      interval: "daily"
